services:
  # Backend API Service (Free)
  - type: web
    name: social-marketplace-api
    runtime: node
    plan: free  # Изменено с starter на free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm run init-db && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: social-marketplace-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false

  # Frontend Static Site (Free)
  - type: web
    name: social-marketplace-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://social-marketplace-api.onrender.com
      - key: REACT_APP_WS_URL
        value: wss://social-marketplace-api.onrender.com

databases:
  # PostgreSQL Database (Free)
  - name: social-marketplace-db
    plan: free  # Изменено с basic-256mb на free
    databaseName: social_marketplace
    user: app_user 